//! File usage lookup
//!
//! Finds the processes currently holding a file open using the Windows
//! Restart Manager, the same machinery installers use to decide what to
//! reboot for: a session is started, the file is registered as the only
//! resource of the session, and the affected process list is read back.
//! On other platforms there is no portable equivalent, so an empty list is
//! reported.

use serde::Serialize;

/// A process currently using a file
#[derive(Serialize, Debug)]
pub struct FileLocker {
    /// PID of the process holding the file open
    pub pid: u32,
    /// Friendly name of the application (Restart Manager's `strAppName`)
    pub app_name: String,
    /// Short name of the service the process belongs to, empty for
    /// non-service processes
    pub short_name: String,
}

/// Returns the processes currently using the given file
///
/// On non-Windows platforms this always returns an empty list: the Restart
/// Manager backing this command only exists on Windows.
pub fn collect(path: &str) -> Result<Vec<FileLocker>, String> {
    platform::collect(path)
}

#[cfg(windows)]
mod platform {
    use super::FileLocker;
    use crate::monitoring::winbuf;
    use windows_sys::core::PCWSTR;
    use windows_sys::Win32::System::RestartManager::{
        CCH_RM_SESSION_KEY, RmEndSession, RmGetList, RmRegisterResources, RmStartSession,
        RM_PROCESS_INFO,
    };

    /// How many times the affected-process list is re-queried with a grown
    /// buffer (processes can appear between the size probe and the copy)
    const MAX_LIST_GROWTH_RETRIES: u32 = 3;

    pub fn collect(path: &str) -> Result<Vec<FileLocker>, String> {
        if path.is_empty() {
            return Err("No file path was given".to_string());
        }
        let path_wide = to_wide(path);
        let files: [PCWSTR; 1] = [path_wide.as_ptr()];
        // The session key is generated by RmStartSession; it needs a buffer
        // of CCH_RM_SESSION_KEY + 1 UTF-16 units
        let mut session_key = [0u16; (CCH_RM_SESSION_KEY + 1) as usize];
        let mut session: u32 = 0;
        // SAFETY: session receives the new handle and session_key is a
        // NUL-initialized buffer of the documented size
        let result = unsafe { RmStartSession(&mut session, 0, session_key.as_mut_ptr()) };
        if result != 0 {
            return Err(format!(
                "Failed to start a Restart Manager session (Windows error {})",
                result
            ));
        }
        // The session is ended on every path once the list has been read
        let outcome = query_lockers(session, &files);
        // SAFETY: session is the valid handle from RmStartSession
        unsafe { RmEndSession(session) };
        outcome
    }

    /// Registers the file with the session and reads back the affected
    /// processes, growing the list buffer as needed
    fn query_lockers(session: u32, files: &[PCWSTR]) -> Result<Vec<FileLocker>, String> {
        // SAFETY: files is a valid array of NUL-terminated paths; no
        // applications or services are registered alongside them
        let result = unsafe {
            RmRegisterResources(
                session,
                files.len() as u32,
                files.as_ptr(),
                0,
                std::ptr::null(),
                0,
                std::ptr::null(),
            )
        };
        if result != 0 {
            return Err(format!(
                "Failed to register the file with the Restart Manager (Windows error {}); the file may not exist",
                result
            ));
        }

        let mut buffer: Vec<RM_PROCESS_INFO> = Vec::new();
        for _ in 0..MAX_LIST_GROWTH_RETRIES {
            let mut needed: u32 = 0;
            let mut count: u32 = buffer.len() as u32;
            let mut reboot_reasons: u32 = 0;
            // SAFETY: buffer holds `count` zeroed RM_PROCESS_INFO entries
            // (every field is u16/u32/i32, so zeroed is a valid value); an
            // empty buffer is passed as null with count 0. needed, count
            // and reboot_reasons are plain out-parameters.
            let result = unsafe {
                RmGetList(
                    session,
                    &mut needed,
                    &mut count,
                    if buffer.is_empty() {
                        std::ptr::null_mut()
                    } else {
                        buffer.as_mut_ptr()
                    },
                    &mut reboot_reasons,
                )
            };
            if result != 0 {
                // RmGetList reports its error code through the return value
                // (not GetLastError); ERROR_MORE_DATA is the documented
                // too-small signal
                if !winbuf::is_buffer_too_small(result) {
                    return Err(format!(
                        "Failed to list the processes using the file (Windows error {})",
                        result
                    ));
                }
                if needed == 0 {
                    return Err(
                        "The Restart Manager reported more data without a size".to_string()
                    );
                }
                buffer = (0..needed).map(|_| unsafe { std::mem::zeroed() }).collect();
                continue;
            }
            let mut lockers = Vec::with_capacity(count as usize);
            for info in buffer.iter().take(count as usize) {
                lockers.push(FileLocker {
                    pid: info.Process.dwProcessId,
                    app_name: wide_string(&info.strAppName),
                    short_name: wide_string(&info.strServiceShortName),
                });
            }
            return Ok(lockers);
        }
        Err(
            "The list of processes using the file changed too often to be read; try again"
                .to_string(),
        )
    }

    /// Reads a NUL-terminated UTF-16 field into a String
    fn wide_string(units: &[u16]) -> String {
        let len = units
            .iter()
            .position(|unit| *unit == 0)
            .unwrap_or(units.len());
        String::from_utf16_lossy(&units[..len])
    }

    /// Encodes a string as a NUL-terminated UTF-16 buffer for Win32 APIs
    fn to_wide(value: &str) -> Vec<u16> {
        value.encode_utf16().chain(std::iter::once(0)).collect()
    }
}

#[cfg(not(windows))]
mod platform {
    pub fn collect(_path: &str) -> Result<Vec<super::FileLocker>, String> {
        // No portable equivalent of the Windows Restart Manager
        Ok(Vec::new())
    }
}
